// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp9cn5Cu9Qy9ouocN1jvHY3tF1yhwhyk4',
    appId: '1:842751979779:web:32dcc4cb3ac45c03dcf936',
    messagingSenderId: '842751979779',
    projectId: 'barber-shop-app-13aa7',
    authDomain: 'barber-shop-app-13aa7.firebaseapp.com',
    storageBucket: 'barber-shop-app-13aa7.firebasestorage.app',
    measurementId: 'G-LXT3WG70S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI2fq0QnKdci-EN2VI0lyOw9Fh-iafVLw',
    appId: '1:842751979779:android:b48f31ca013180a8dcf936',
    messagingSenderId: '842751979779',
    projectId: 'barber-shop-app-13aa7',
    storageBucket: 'barber-shop-app-13aa7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvm6KHosyy_vFCo8AfB3S7Nv958g8rqHw',
    appId: '1:842751979779:ios:92e0acb870a5ecacdcf936',
    messagingSenderId: '842751979779',
    projectId: 'barber-shop-app-13aa7',
    storageBucket: 'barber-shop-app-13aa7.firebasestorage.app',
    iosBundleId: 'com.zurano.barbershop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvm6KHosyy_vFCo8AfB3S7Nv958g8rqHw',
    appId: '1:842751979779:ios:968096d2858bdb8adcf936',
    messagingSenderId: '842751979779',
    projectId: 'barber-shop-app-13aa7',
    storageBucket: 'barber-shop-app-13aa7.firebasestorage.app',
    iosBundleId: 'com.example.barberShopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp9cn5Cu9Qy9ouocN1jvHY3tF1yhwhyk4',
    appId: '1:842751979779:web:f4608dc8ea3cd134dcf936',
    messagingSenderId: '842751979779',
    projectId: 'barber-shop-app-13aa7',
    authDomain: 'barber-shop-app-13aa7.firebaseapp.com',
    storageBucket: 'barber-shop-app-13aa7.firebasestorage.app',
    measurementId: 'G-G5VTVXWGRR',
  );
}
